name: workflow on pull request
on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: pip install mypy
      - run: mypy --strict src
