name: workflow on push to main or develop
on:
  push:
    branches:
      - main
      - develop
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: pip install mypy
      - run: mypy --strict src

  build-and-publish:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ github.repository }}:${{ github.sha }}
            ${{ github.repository }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-publish
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: ./deploy.sh
          script_stop: true
